### PR TITLE
Fix crash when applying "on-top" rules to ES6 modules

### LINKED ISSUE #66: Exporting a variable called events causes an error
``` javascript
var events = {};
export default events;
```

results in the following stack trace:

```
TypeError: Cannot read property 'type' of null
    at isBackboneBase (node_modules/eslint-plugin-backbone/lib/backbone-helper.js:9:16)
    at isBackboneView (node_modules/eslint-plugin-backbone/lib/backbone-helper.js:56:12)
    at Object.exports.checkIfPropertyInBackboneView (node_modules/eslint-plugin-backbone/lib/backbone-helper.js:91:12)
    at EventEmitter.Identifier (node_modules/eslint-plugin-backbone/lib/rules/events-on-top.js:43:32)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (node_modules/eslint/lib/eslint.js:895:36)
```

### PR DESCRIPTION
**Pull request by brianhelba**
* Add tests for applying `on-top` rules to ES6 modules
* Fix crash when applying `on-top` rules to ES6 modules
  * The greatgrandparent of an ES6 module "export" statement is null. Avoid further inspection of these nodes in "checkIfPropertyInBackboneModel" by first checking whether they are part of an "ObjectExpression" at all.

Fixes #66

### CODE REVIEW

**Comment by brianhelba** [comment]
@ilyavolodin Please take a look.

I realize that the test code I added goes a little outside the scope of the existing tests, as it validates totally non-Backbone syntax. If you'd like to keep the tests "pure", I can remove that commit. I just wanted to demonstrate the error and the working fix for the purposes of this PR.

File: tests/lib/rules/defaults-on-top.js [hunk 1]
```diff
@@ -44,3 +45,16 @@ eslintTester.run("defaults-on-top", rule, {
         }
     ]
 });
+
+eslintTester = new RuleTester({
```
Comment (ilyavolodin) [inline tests/lib/rules/defaults-on-top.js]: I think it's easier to just have one RuleTester with below `parserOptions` they shouldn't conflict with existing tests. And creating multiple instance of RuleTester is a bit confusing.

Comment (brianhelba) [inline tests/lib/rules/defaults-on-top.js]: @ilyavolodin Will do.

**Comment by brianhelba** [comment]
@ilyavolodin Updated.

**Comment by ilyavolodin** [comment]
LGTM, thanks.
